config/routes.rb
Rails.application.routes.draw do
  get root to: 'books#top'
  get 'books' => 'books#index'
  get 'books/:id' => 'books#show', as: 'book'
  get 'books/new'
  post 'books' => 'books#create'
  get 'books/:id/edit' => 'books#edit', as: 'edit_book'
  patch 'books/:id' => 'books#update', as: 'update_book'
  delete 'books/:id' => 'books#destroy', as: 'destroy_book'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
  validates :title, :body, presence: true

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  def index
    @books = Book.all
    @book = Book.new
  end

  def show
    @book = Book.find(params[:id])
  end

  def create
    @book = Book.new(book_params)
    if @book.save
      redirect_to book_path(@book.id)
      flash[:create] = "Book was successfully created."
    else
      # コントローラを通さないのでここに@booksを定義する
      @books = Book.all
      render :index
# バリデーション対応がしたい。空白の場合動かない。renderがわからない。

    end
  end

  def edit
    @book = Book.find(params[:id])

  end

  def update
    @book = Book.find(params[:id])
    if @book.update(book_params)
      redirect_to book_path(@book.id)
      flash[:update] = "Book was successfully updated."
    else
      render :edit
    end
  end

  def destroy
    book = Book.find(params[:id])
    book.destroy
    redirect_to books_path
    flash[:destroy] = "Book was successfully destroyed."

  end

  private
  def book_params
    params.require(:book).permit(:title, :body)
    # ストロングパラメータがわからない
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/views/books/_error_form.html.erb
<% if @book.errors.any? %>
  <div id="error_explanation">
    <p><%= pluralize(@book.errors.count, "error") %> prohibited this book from being saved:</p>
   <!--エラーの数を数える-->
    <ul>
      <% @book.errors.full_messages.each do |message| %>
      　<li><%= message %></li>
      　<!--エラー文は自動で作られる-->

      <% end %>
    </ul>
  </div>
<% end %>

app/views/books/edit.html.erb
<%= render partial: 'error_form' %>
<h1>Editing Book</h1>
<%= form_with model:@book, url:"/books/#{@book.id}", local:true do |f| %>
  <h4>Title</h4>
  <%= f.text_field :title %>
  <h4>Body</h4>
  <%= f.text_area :body %>

  <p><%= f.submit "Update Book" %></p>

  <th><%= link_to "show", book_path(@book.id) %></th> |
  <th><a class="back" href="/books">Back</a></th>
<% end %>

app/views/books/index.html.erb
<!DOCTYPE html>
<html>
  <body>
    <p><%= flash[:destroy] %></p>
    <h1>Books</h1>
    <table
      <thead>
        <tr>
          <th>Title</th>
          <th>Body</th>
          <th colspan="3"></th>
        </tr>
      </thead>
      <tbody>
        <% @books.each do |book| %>
        <tr>
          <td><%= book.title %></td>
          <td><%= book.body %></td>
          <td><%= link_to "Show", book_path(book.id) %></td>
          <td><%= link_to "Edit", edit_book_path(book.id) %></td>
          <td><%= link_to "Destroy", destroy_book_path(book.id), method: :delete, "data-confirm" => "Are you sure?" %></td>
        </tr>
        <% end %>
      </tbody>
    </table>

    <h1>New Book</h1>
    <%= render partial: 'error_form' %>
    <%= form_with model:@book, url:"/books", local:true do |f| %>
      <h4>Title</h4>
      <%= f.text_field :title %>
      <h4>Body</h4>
      <%= f.text_area :body %>
      <p><%= f.submit "Create Book" %></p>
    <% end %>
  </body>
</html>

app/views/books/show.html.erb
<p><%= flash[:create] %></p>
<p><%= flash[:update] %></p>

<%= form_with model:@book, url:"/books/#{@book.id}", local:true do |f| %>
  <p>Title:<%= @book.title %></p>
  <p>Body:<%= @book.body %></p>

  <th><%= link_to "Edit", edit_book_path(@book.id) %></th> |
  <th><a class="back" href="/books">Back</a></th>
<% end %>

app/views/books/top.html.erb
<!DOCTYPE html>
<html>
    <body>
        <h1>ようこそ<strong>Bookers</strong>へ！</h1>
        <p><strong>Bookers</strong>では、さまざまな書籍に関するあなたの意見や</p>
        <p>印象を共有し交換することができます</p>
        <p><a href="/books">start</a></p>
    </body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bookers</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>